apiVersion: v1
kind: Service
metadata:
  name: actorgateway-micronaut
  labels:
    name: actorgateway-micronaut
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8080
    - name: grpc
      port: 50051
  selector:
    app:  actorgateway-micronaut