apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "actornode-micronaut"
spec:
  serviceName: "actornode-micronaut"
  selector:
    matchLabels:
      app: "actornode-micronaut"
  template:
    metadata:
      labels:
        app: "actornode-micronaut"
    spec:
      serviceAccountName: "elasticactors-operator"
      containers:
        - name: "actornode-micronaut"
          image: "actornode-micronaut"
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 50051
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
#          livenessProbe:
#            httpGet:
#              path: /health
#              port: 8080
#            initialDelaySeconds: 5
#            timeoutSeconds: 3
#            failureThreshold: 10
