---
micronaut:
  application:
    name: persistentactor-micronaut

---
micronaut:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

grpc:
  client:
    plaintext: true
