// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package org.elasticsoftware.elasticactors.grpc;

public interface ActorLifecycleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
   */
  java.util.List<org.elasticsoftware.elasticactors.grpc.InternalMessage> 
      getMessagesList();
  /**
   * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
   */
  org.elasticsoftware.elasticactors.grpc.InternalMessage getMessages(int index);
  /**
   * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
   */
  java.util.List<? extends org.elasticsoftware.elasticactors.grpc.InternalMessageOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
   */
  org.elasticsoftware.elasticactors.grpc.InternalMessageOrBuilder getMessagesOrBuilder(
      int index);

  /**
   * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
   * @return Whether the state field is set.
   */
  boolean hasState();
  /**
   * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
   * @return The state.
   */
  org.elasticsoftware.elasticactors.grpc.ActorState getState();
  /**
   * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
   */
  org.elasticsoftware.elasticactors.grpc.ActorStateOrBuilder getStateOrBuilder();
}
