// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package org.elasticsoftware.elasticactors.grpc;

/**
 * Protobuf type {@code org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse}
 */
public  final class ActorLifecycleResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse)
    ActorLifecycleResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ActorLifecycleResponse.newBuilder() to construct.
  private ActorLifecycleResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ActorLifecycleResponse() {
    messages_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ActorLifecycleResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ActorLifecycleResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              messages_ = new java.util.ArrayList<org.elasticsoftware.elasticactors.grpc.InternalMessage>();
              mutable_bitField0_ |= 0x00000001;
            }
            messages_.add(
                input.readMessage(org.elasticsoftware.elasticactors.grpc.InternalMessage.parser(), extensionRegistry));
            break;
          }
          case 18: {
            org.elasticsoftware.elasticactors.grpc.ActorState.Builder subBuilder = null;
            if (state_ != null) {
              subBuilder = state_.toBuilder();
            }
            state_ = input.readMessage(org.elasticsoftware.elasticactors.grpc.ActorState.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(state_);
              state_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        messages_ = java.util.Collections.unmodifiableList(messages_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.elasticsoftware.elasticactors.grpc.Services.internal_static_org_elasticsoftware_elasticactors_grpc_ActorLifecycleResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.elasticsoftware.elasticactors.grpc.Services.internal_static_org_elasticsoftware_elasticactors_grpc_ActorLifecycleResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse.class, org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse.Builder.class);
  }

  public static final int MESSAGES_FIELD_NUMBER = 1;
  private java.util.List<org.elasticsoftware.elasticactors.grpc.InternalMessage> messages_;
  /**
   * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
   */
  public java.util.List<org.elasticsoftware.elasticactors.grpc.InternalMessage> getMessagesList() {
    return messages_;
  }
  /**
   * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
   */
  public java.util.List<? extends org.elasticsoftware.elasticactors.grpc.InternalMessageOrBuilder> 
      getMessagesOrBuilderList() {
    return messages_;
  }
  /**
   * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
   */
  public int getMessagesCount() {
    return messages_.size();
  }
  /**
   * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
   */
  public org.elasticsoftware.elasticactors.grpc.InternalMessage getMessages(int index) {
    return messages_.get(index);
  }
  /**
   * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
   */
  public org.elasticsoftware.elasticactors.grpc.InternalMessageOrBuilder getMessagesOrBuilder(
      int index) {
    return messages_.get(index);
  }

  public static final int STATE_FIELD_NUMBER = 2;
  private org.elasticsoftware.elasticactors.grpc.ActorState state_;
  /**
   * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
   * @return Whether the state field is set.
   */
  public boolean hasState() {
    return state_ != null;
  }
  /**
   * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
   * @return The state.
   */
  public org.elasticsoftware.elasticactors.grpc.ActorState getState() {
    return state_ == null ? org.elasticsoftware.elasticactors.grpc.ActorState.getDefaultInstance() : state_;
  }
  /**
   * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
   */
  public org.elasticsoftware.elasticactors.grpc.ActorStateOrBuilder getStateOrBuilder() {
    return getState();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < messages_.size(); i++) {
      output.writeMessage(1, messages_.get(i));
    }
    if (state_ != null) {
      output.writeMessage(2, getState());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < messages_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, messages_.get(i));
    }
    if (state_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getState());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse)) {
      return super.equals(obj);
    }
    org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse other = (org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse) obj;

    if (!getMessagesList()
        .equals(other.getMessagesList())) return false;
    if (hasState() != other.hasState()) return false;
    if (hasState()) {
      if (!getState()
          .equals(other.getState())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMessagesCount() > 0) {
      hash = (37 * hash) + MESSAGES_FIELD_NUMBER;
      hash = (53 * hash) + getMessagesList().hashCode();
    }
    if (hasState()) {
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse)
      org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.elasticsoftware.elasticactors.grpc.Services.internal_static_org_elasticsoftware_elasticactors_grpc_ActorLifecycleResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.elasticsoftware.elasticactors.grpc.Services.internal_static_org_elasticsoftware_elasticactors_grpc_ActorLifecycleResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse.class, org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse.Builder.class);
    }

    // Construct using org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMessagesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (messagesBuilder_ == null) {
        messages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        messagesBuilder_.clear();
      }
      if (stateBuilder_ == null) {
        state_ = null;
      } else {
        state_ = null;
        stateBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.elasticsoftware.elasticactors.grpc.Services.internal_static_org_elasticsoftware_elasticactors_grpc_ActorLifecycleResponse_descriptor;
    }

    @java.lang.Override
    public org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse getDefaultInstanceForType() {
      return org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse build() {
      org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse buildPartial() {
      org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse result = new org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse(this);
      int from_bitField0_ = bitField0_;
      if (messagesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          messages_ = java.util.Collections.unmodifiableList(messages_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.messages_ = messages_;
      } else {
        result.messages_ = messagesBuilder_.build();
      }
      if (stateBuilder_ == null) {
        result.state_ = state_;
      } else {
        result.state_ = stateBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse) {
        return mergeFrom((org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse other) {
      if (other == org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse.getDefaultInstance()) return this;
      if (messagesBuilder_ == null) {
        if (!other.messages_.isEmpty()) {
          if (messages_.isEmpty()) {
            messages_ = other.messages_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMessagesIsMutable();
            messages_.addAll(other.messages_);
          }
          onChanged();
        }
      } else {
        if (!other.messages_.isEmpty()) {
          if (messagesBuilder_.isEmpty()) {
            messagesBuilder_.dispose();
            messagesBuilder_ = null;
            messages_ = other.messages_;
            bitField0_ = (bitField0_ & ~0x00000001);
            messagesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMessagesFieldBuilder() : null;
          } else {
            messagesBuilder_.addAllMessages(other.messages_);
          }
        }
      }
      if (other.hasState()) {
        mergeState(other.getState());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.elasticsoftware.elasticactors.grpc.InternalMessage> messages_ =
      java.util.Collections.emptyList();
    private void ensureMessagesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        messages_ = new java.util.ArrayList<org.elasticsoftware.elasticactors.grpc.InternalMessage>(messages_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.elasticsoftware.elasticactors.grpc.InternalMessage, org.elasticsoftware.elasticactors.grpc.InternalMessage.Builder, org.elasticsoftware.elasticactors.grpc.InternalMessageOrBuilder> messagesBuilder_;

    /**
     * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
     */
    public java.util.List<org.elasticsoftware.elasticactors.grpc.InternalMessage> getMessagesList() {
      if (messagesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(messages_);
      } else {
        return messagesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
     */
    public int getMessagesCount() {
      if (messagesBuilder_ == null) {
        return messages_.size();
      } else {
        return messagesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
     */
    public org.elasticsoftware.elasticactors.grpc.InternalMessage getMessages(int index) {
      if (messagesBuilder_ == null) {
        return messages_.get(index);
      } else {
        return messagesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
     */
    public Builder setMessages(
        int index, org.elasticsoftware.elasticactors.grpc.InternalMessage value) {
      if (messagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessagesIsMutable();
        messages_.set(index, value);
        onChanged();
      } else {
        messagesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
     */
    public Builder setMessages(
        int index, org.elasticsoftware.elasticactors.grpc.InternalMessage.Builder builderForValue) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.set(index, builderForValue.build());
        onChanged();
      } else {
        messagesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
     */
    public Builder addMessages(org.elasticsoftware.elasticactors.grpc.InternalMessage value) {
      if (messagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessagesIsMutable();
        messages_.add(value);
        onChanged();
      } else {
        messagesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
     */
    public Builder addMessages(
        int index, org.elasticsoftware.elasticactors.grpc.InternalMessage value) {
      if (messagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessagesIsMutable();
        messages_.add(index, value);
        onChanged();
      } else {
        messagesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
     */
    public Builder addMessages(
        org.elasticsoftware.elasticactors.grpc.InternalMessage.Builder builderForValue) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.add(builderForValue.build());
        onChanged();
      } else {
        messagesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
     */
    public Builder addMessages(
        int index, org.elasticsoftware.elasticactors.grpc.InternalMessage.Builder builderForValue) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.add(index, builderForValue.build());
        onChanged();
      } else {
        messagesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
     */
    public Builder addAllMessages(
        java.lang.Iterable<? extends org.elasticsoftware.elasticactors.grpc.InternalMessage> values) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, messages_);
        onChanged();
      } else {
        messagesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
     */
    public Builder clearMessages() {
      if (messagesBuilder_ == null) {
        messages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        messagesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
     */
    public Builder removeMessages(int index) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.remove(index);
        onChanged();
      } else {
        messagesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
     */
    public org.elasticsoftware.elasticactors.grpc.InternalMessage.Builder getMessagesBuilder(
        int index) {
      return getMessagesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
     */
    public org.elasticsoftware.elasticactors.grpc.InternalMessageOrBuilder getMessagesOrBuilder(
        int index) {
      if (messagesBuilder_ == null) {
        return messages_.get(index);  } else {
        return messagesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
     */
    public java.util.List<? extends org.elasticsoftware.elasticactors.grpc.InternalMessageOrBuilder> 
         getMessagesOrBuilderList() {
      if (messagesBuilder_ != null) {
        return messagesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(messages_);
      }
    }
    /**
     * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
     */
    public org.elasticsoftware.elasticactors.grpc.InternalMessage.Builder addMessagesBuilder() {
      return getMessagesFieldBuilder().addBuilder(
          org.elasticsoftware.elasticactors.grpc.InternalMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
     */
    public org.elasticsoftware.elasticactors.grpc.InternalMessage.Builder addMessagesBuilder(
        int index) {
      return getMessagesFieldBuilder().addBuilder(
          index, org.elasticsoftware.elasticactors.grpc.InternalMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .org.elasticsoftware.elasticactors.grpc.InternalMessage messages = 1;</code>
     */
    public java.util.List<org.elasticsoftware.elasticactors.grpc.InternalMessage.Builder> 
         getMessagesBuilderList() {
      return getMessagesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.elasticsoftware.elasticactors.grpc.InternalMessage, org.elasticsoftware.elasticactors.grpc.InternalMessage.Builder, org.elasticsoftware.elasticactors.grpc.InternalMessageOrBuilder> 
        getMessagesFieldBuilder() {
      if (messagesBuilder_ == null) {
        messagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.elasticsoftware.elasticactors.grpc.InternalMessage, org.elasticsoftware.elasticactors.grpc.InternalMessage.Builder, org.elasticsoftware.elasticactors.grpc.InternalMessageOrBuilder>(
                messages_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        messages_ = null;
      }
      return messagesBuilder_;
    }

    private org.elasticsoftware.elasticactors.grpc.ActorState state_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.elasticsoftware.elasticactors.grpc.ActorState, org.elasticsoftware.elasticactors.grpc.ActorState.Builder, org.elasticsoftware.elasticactors.grpc.ActorStateOrBuilder> stateBuilder_;
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
     * @return Whether the state field is set.
     */
    public boolean hasState() {
      return stateBuilder_ != null || state_ != null;
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
     * @return The state.
     */
    public org.elasticsoftware.elasticactors.grpc.ActorState getState() {
      if (stateBuilder_ == null) {
        return state_ == null ? org.elasticsoftware.elasticactors.grpc.ActorState.getDefaultInstance() : state_;
      } else {
        return stateBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
     */
    public Builder setState(org.elasticsoftware.elasticactors.grpc.ActorState value) {
      if (stateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        state_ = value;
        onChanged();
      } else {
        stateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
     */
    public Builder setState(
        org.elasticsoftware.elasticactors.grpc.ActorState.Builder builderForValue) {
      if (stateBuilder_ == null) {
        state_ = builderForValue.build();
        onChanged();
      } else {
        stateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
     */
    public Builder mergeState(org.elasticsoftware.elasticactors.grpc.ActorState value) {
      if (stateBuilder_ == null) {
        if (state_ != null) {
          state_ =
            org.elasticsoftware.elasticactors.grpc.ActorState.newBuilder(state_).mergeFrom(value).buildPartial();
        } else {
          state_ = value;
        }
        onChanged();
      } else {
        stateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
     */
    public Builder clearState() {
      if (stateBuilder_ == null) {
        state_ = null;
        onChanged();
      } else {
        state_ = null;
        stateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
     */
    public org.elasticsoftware.elasticactors.grpc.ActorState.Builder getStateBuilder() {
      
      onChanged();
      return getStateFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
     */
    public org.elasticsoftware.elasticactors.grpc.ActorStateOrBuilder getStateOrBuilder() {
      if (stateBuilder_ != null) {
        return stateBuilder_.getMessageOrBuilder();
      } else {
        return state_ == null ?
            org.elasticsoftware.elasticactors.grpc.ActorState.getDefaultInstance() : state_;
      }
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.elasticsoftware.elasticactors.grpc.ActorState, org.elasticsoftware.elasticactors.grpc.ActorState.Builder, org.elasticsoftware.elasticactors.grpc.ActorStateOrBuilder> 
        getStateFieldBuilder() {
      if (stateBuilder_ == null) {
        stateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.elasticsoftware.elasticactors.grpc.ActorState, org.elasticsoftware.elasticactors.grpc.ActorState.Builder, org.elasticsoftware.elasticactors.grpc.ActorStateOrBuilder>(
                getState(),
                getParentForChildren(),
                isClean());
        state_ = null;
      }
      return stateBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse)
  }

  // @@protoc_insertion_point(class_scope:org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse)
  private static final org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse();
  }

  public static org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ActorLifecycleResponse>
      PARSER = new com.google.protobuf.AbstractParser<ActorLifecycleResponse>() {
    @java.lang.Override
    public ActorLifecycleResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ActorLifecycleResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ActorLifecycleResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ActorLifecycleResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.elasticsoftware.elasticactors.grpc.ActorLifecycleResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

