// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package org.elasticsoftware.elasticactors.grpc;

/**
 * <pre>
 * The current serialized actor state
 * </pre>
 *
 * Protobuf type {@code org.elasticsoftware.elasticactors.grpc.ActorState}
 */
public  final class ActorState extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.elasticsoftware.elasticactors.grpc.ActorState)
    ActorStateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ActorState.newBuilder() to construct.
  private ActorState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ActorState() {
    state_ = com.google.protobuf.ByteString.EMPTY;
    compressionMethod_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ActorState();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ActorState(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            state_ = input.readBytes();
            break;
          }
          case 16: {

            stateGeneration_ = input.readUInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            compressionMethod_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.elasticsoftware.elasticactors.grpc.Services.internal_static_org_elasticsoftware_elasticactors_grpc_ActorState_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.elasticsoftware.elasticactors.grpc.Services.internal_static_org_elasticsoftware_elasticactors_grpc_ActorState_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.elasticsoftware.elasticactors.grpc.ActorState.class, org.elasticsoftware.elasticactors.grpc.ActorState.Builder.class);
  }

  public static final int STATE_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString state_;
  /**
   * <code>bytes state = 1;</code>
   * @return The state.
   */
  public com.google.protobuf.ByteString getState() {
    return state_;
  }

  public static final int STATEGENERATION_FIELD_NUMBER = 2;
  private long stateGeneration_;
  /**
   * <code>uint64 stateGeneration = 2;</code>
   * @return The stateGeneration.
   */
  public long getStateGeneration() {
    return stateGeneration_;
  }

  public static final int COMPRESSIONMETHOD_FIELD_NUMBER = 3;
  private volatile java.lang.Object compressionMethod_;
  /**
   * <code>string compressionMethod = 3;</code>
   * @return The compressionMethod.
   */
  public java.lang.String getCompressionMethod() {
    java.lang.Object ref = compressionMethod_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      compressionMethod_ = s;
      return s;
    }
  }
  /**
   * <code>string compressionMethod = 3;</code>
   * @return The bytes for compressionMethod.
   */
  public com.google.protobuf.ByteString
      getCompressionMethodBytes() {
    java.lang.Object ref = compressionMethod_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      compressionMethod_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!state_.isEmpty()) {
      output.writeBytes(1, state_);
    }
    if (stateGeneration_ != 0L) {
      output.writeUInt64(2, stateGeneration_);
    }
    if (!getCompressionMethodBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, compressionMethod_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!state_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, state_);
    }
    if (stateGeneration_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, stateGeneration_);
    }
    if (!getCompressionMethodBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, compressionMethod_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.elasticsoftware.elasticactors.grpc.ActorState)) {
      return super.equals(obj);
    }
    org.elasticsoftware.elasticactors.grpc.ActorState other = (org.elasticsoftware.elasticactors.grpc.ActorState) obj;

    if (!getState()
        .equals(other.getState())) return false;
    if (getStateGeneration()
        != other.getStateGeneration()) return false;
    if (!getCompressionMethod()
        .equals(other.getCompressionMethod())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATE_FIELD_NUMBER;
    hash = (53 * hash) + getState().hashCode();
    hash = (37 * hash) + STATEGENERATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStateGeneration());
    hash = (37 * hash) + COMPRESSIONMETHOD_FIELD_NUMBER;
    hash = (53 * hash) + getCompressionMethod().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.elasticsoftware.elasticactors.grpc.ActorState parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.elasticsoftware.elasticactors.grpc.ActorState parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.elasticsoftware.elasticactors.grpc.ActorState parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.elasticsoftware.elasticactors.grpc.ActorState parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.elasticsoftware.elasticactors.grpc.ActorState parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.elasticsoftware.elasticactors.grpc.ActorState parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.elasticsoftware.elasticactors.grpc.ActorState parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.elasticsoftware.elasticactors.grpc.ActorState parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.elasticsoftware.elasticactors.grpc.ActorState parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.elasticsoftware.elasticactors.grpc.ActorState parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.elasticsoftware.elasticactors.grpc.ActorState parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.elasticsoftware.elasticactors.grpc.ActorState parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.elasticsoftware.elasticactors.grpc.ActorState prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The current serialized actor state
   * </pre>
   *
   * Protobuf type {@code org.elasticsoftware.elasticactors.grpc.ActorState}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.elasticsoftware.elasticactors.grpc.ActorState)
      org.elasticsoftware.elasticactors.grpc.ActorStateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.elasticsoftware.elasticactors.grpc.Services.internal_static_org_elasticsoftware_elasticactors_grpc_ActorState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.elasticsoftware.elasticactors.grpc.Services.internal_static_org_elasticsoftware_elasticactors_grpc_ActorState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.elasticsoftware.elasticactors.grpc.ActorState.class, org.elasticsoftware.elasticactors.grpc.ActorState.Builder.class);
    }

    // Construct using org.elasticsoftware.elasticactors.grpc.ActorState.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      state_ = com.google.protobuf.ByteString.EMPTY;

      stateGeneration_ = 0L;

      compressionMethod_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.elasticsoftware.elasticactors.grpc.Services.internal_static_org_elasticsoftware_elasticactors_grpc_ActorState_descriptor;
    }

    @java.lang.Override
    public org.elasticsoftware.elasticactors.grpc.ActorState getDefaultInstanceForType() {
      return org.elasticsoftware.elasticactors.grpc.ActorState.getDefaultInstance();
    }

    @java.lang.Override
    public org.elasticsoftware.elasticactors.grpc.ActorState build() {
      org.elasticsoftware.elasticactors.grpc.ActorState result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.elasticsoftware.elasticactors.grpc.ActorState buildPartial() {
      org.elasticsoftware.elasticactors.grpc.ActorState result = new org.elasticsoftware.elasticactors.grpc.ActorState(this);
      result.state_ = state_;
      result.stateGeneration_ = stateGeneration_;
      result.compressionMethod_ = compressionMethod_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.elasticsoftware.elasticactors.grpc.ActorState) {
        return mergeFrom((org.elasticsoftware.elasticactors.grpc.ActorState)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.elasticsoftware.elasticactors.grpc.ActorState other) {
      if (other == org.elasticsoftware.elasticactors.grpc.ActorState.getDefaultInstance()) return this;
      if (other.getState() != com.google.protobuf.ByteString.EMPTY) {
        setState(other.getState());
      }
      if (other.getStateGeneration() != 0L) {
        setStateGeneration(other.getStateGeneration());
      }
      if (!other.getCompressionMethod().isEmpty()) {
        compressionMethod_ = other.compressionMethod_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.elasticsoftware.elasticactors.grpc.ActorState parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.elasticsoftware.elasticactors.grpc.ActorState) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString state_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes state = 1;</code>
     * @return The state.
     */
    public com.google.protobuf.ByteString getState() {
      return state_;
    }
    /**
     * <code>bytes state = 1;</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setState(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      state_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes state = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      
      state_ = getDefaultInstance().getState();
      onChanged();
      return this;
    }

    private long stateGeneration_ ;
    /**
     * <code>uint64 stateGeneration = 2;</code>
     * @return The stateGeneration.
     */
    public long getStateGeneration() {
      return stateGeneration_;
    }
    /**
     * <code>uint64 stateGeneration = 2;</code>
     * @param value The stateGeneration to set.
     * @return This builder for chaining.
     */
    public Builder setStateGeneration(long value) {
      
      stateGeneration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 stateGeneration = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStateGeneration() {
      
      stateGeneration_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object compressionMethod_ = "";
    /**
     * <code>string compressionMethod = 3;</code>
     * @return The compressionMethod.
     */
    public java.lang.String getCompressionMethod() {
      java.lang.Object ref = compressionMethod_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        compressionMethod_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string compressionMethod = 3;</code>
     * @return The bytes for compressionMethod.
     */
    public com.google.protobuf.ByteString
        getCompressionMethodBytes() {
      java.lang.Object ref = compressionMethod_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        compressionMethod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string compressionMethod = 3;</code>
     * @param value The compressionMethod to set.
     * @return This builder for chaining.
     */
    public Builder setCompressionMethod(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      compressionMethod_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string compressionMethod = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompressionMethod() {
      
      compressionMethod_ = getDefaultInstance().getCompressionMethod();
      onChanged();
      return this;
    }
    /**
     * <code>string compressionMethod = 3;</code>
     * @param value The bytes for compressionMethod to set.
     * @return This builder for chaining.
     */
    public Builder setCompressionMethodBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      compressionMethod_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.elasticsoftware.elasticactors.grpc.ActorState)
  }

  // @@protoc_insertion_point(class_scope:org.elasticsoftware.elasticactors.grpc.ActorState)
  private static final org.elasticsoftware.elasticactors.grpc.ActorState DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.elasticsoftware.elasticactors.grpc.ActorState();
  }

  public static org.elasticsoftware.elasticactors.grpc.ActorState getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ActorState>
      PARSER = new com.google.protobuf.AbstractParser<ActorState>() {
    @java.lang.Override
    public ActorState parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ActorState(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ActorState> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ActorState> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.elasticsoftware.elasticactors.grpc.ActorState getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

