// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package org.elasticsoftware.elasticactors.grpc;

public interface ActorStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.elasticsoftware.elasticactors.grpc.ActorState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes state = 1;</code>
   * @return The state.
   */
  com.google.protobuf.ByteString getState();

  /**
   * <code>uint64 stateGeneration = 2;</code>
   * @return The stateGeneration.
   */
  long getStateGeneration();

  /**
   * <code>string compressionMethod = 3;</code>
   * @return The compressionMethod.
   */
  java.lang.String getCompressionMethod();
  /**
   * <code>string compressionMethod = 3;</code>
   * @return The bytes for compressionMethod.
   */
  com.google.protobuf.ByteString
      getCompressionMethodBytes();
}
