// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package org.elasticsoftware.elasticactors.grpc;

public interface HandleMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.elasticsoftware.elasticactors.grpc.HandleMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.elasticsoftware.elasticactors.grpc.InternalMessage message = 1;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>.org.elasticsoftware.elasticactors.grpc.InternalMessage message = 1;</code>
   * @return The message.
   */
  org.elasticsoftware.elasticactors.grpc.InternalMessage getMessage();
  /**
   * <code>.org.elasticsoftware.elasticactors.grpc.InternalMessage message = 1;</code>
   */
  org.elasticsoftware.elasticactors.grpc.InternalMessageOrBuilder getMessageOrBuilder();

  /**
   * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
   * @return Whether the state field is set.
   */
  boolean hasState();
  /**
   * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
   * @return The state.
   */
  org.elasticsoftware.elasticactors.grpc.ActorState getState();
  /**
   * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
   */
  org.elasticsoftware.elasticactors.grpc.ActorStateOrBuilder getStateOrBuilder();
}
