// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package org.elasticsoftware.elasticactors.grpc;

/**
 * <pre>
 * The request message with the actor name.
 * </pre>
 *
 * Protobuf type {@code org.elasticsoftware.elasticactors.grpc.HandleMessageRequest}
 */
public  final class HandleMessageRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.elasticsoftware.elasticactors.grpc.HandleMessageRequest)
    HandleMessageRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HandleMessageRequest.newBuilder() to construct.
  private HandleMessageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HandleMessageRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HandleMessageRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HandleMessageRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.elasticsoftware.elasticactors.grpc.InternalMessage.Builder subBuilder = null;
            if (message_ != null) {
              subBuilder = message_.toBuilder();
            }
            message_ = input.readMessage(org.elasticsoftware.elasticactors.grpc.InternalMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(message_);
              message_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            org.elasticsoftware.elasticactors.grpc.ActorState.Builder subBuilder = null;
            if (state_ != null) {
              subBuilder = state_.toBuilder();
            }
            state_ = input.readMessage(org.elasticsoftware.elasticactors.grpc.ActorState.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(state_);
              state_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.elasticsoftware.elasticactors.grpc.Services.internal_static_org_elasticsoftware_elasticactors_grpc_HandleMessageRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.elasticsoftware.elasticactors.grpc.Services.internal_static_org_elasticsoftware_elasticactors_grpc_HandleMessageRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.elasticsoftware.elasticactors.grpc.HandleMessageRequest.class, org.elasticsoftware.elasticactors.grpc.HandleMessageRequest.Builder.class);
  }

  public static final int MESSAGE_FIELD_NUMBER = 1;
  private org.elasticsoftware.elasticactors.grpc.InternalMessage message_;
  /**
   * <code>.org.elasticsoftware.elasticactors.grpc.InternalMessage message = 1;</code>
   * @return Whether the message field is set.
   */
  public boolean hasMessage() {
    return message_ != null;
  }
  /**
   * <code>.org.elasticsoftware.elasticactors.grpc.InternalMessage message = 1;</code>
   * @return The message.
   */
  public org.elasticsoftware.elasticactors.grpc.InternalMessage getMessage() {
    return message_ == null ? org.elasticsoftware.elasticactors.grpc.InternalMessage.getDefaultInstance() : message_;
  }
  /**
   * <code>.org.elasticsoftware.elasticactors.grpc.InternalMessage message = 1;</code>
   */
  public org.elasticsoftware.elasticactors.grpc.InternalMessageOrBuilder getMessageOrBuilder() {
    return getMessage();
  }

  public static final int STATE_FIELD_NUMBER = 2;
  private org.elasticsoftware.elasticactors.grpc.ActorState state_;
  /**
   * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
   * @return Whether the state field is set.
   */
  public boolean hasState() {
    return state_ != null;
  }
  /**
   * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
   * @return The state.
   */
  public org.elasticsoftware.elasticactors.grpc.ActorState getState() {
    return state_ == null ? org.elasticsoftware.elasticactors.grpc.ActorState.getDefaultInstance() : state_;
  }
  /**
   * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
   */
  public org.elasticsoftware.elasticactors.grpc.ActorStateOrBuilder getStateOrBuilder() {
    return getState();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (message_ != null) {
      output.writeMessage(1, getMessage());
    }
    if (state_ != null) {
      output.writeMessage(2, getState());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (message_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMessage());
    }
    if (state_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getState());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.elasticsoftware.elasticactors.grpc.HandleMessageRequest)) {
      return super.equals(obj);
    }
    org.elasticsoftware.elasticactors.grpc.HandleMessageRequest other = (org.elasticsoftware.elasticactors.grpc.HandleMessageRequest) obj;

    if (hasMessage() != other.hasMessage()) return false;
    if (hasMessage()) {
      if (!getMessage()
          .equals(other.getMessage())) return false;
    }
    if (hasState() != other.hasState()) return false;
    if (hasState()) {
      if (!getState()
          .equals(other.getState())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMessage()) {
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
    }
    if (hasState()) {
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.elasticsoftware.elasticactors.grpc.HandleMessageRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.elasticsoftware.elasticactors.grpc.HandleMessageRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.elasticsoftware.elasticactors.grpc.HandleMessageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.elasticsoftware.elasticactors.grpc.HandleMessageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.elasticsoftware.elasticactors.grpc.HandleMessageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.elasticsoftware.elasticactors.grpc.HandleMessageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.elasticsoftware.elasticactors.grpc.HandleMessageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.elasticsoftware.elasticactors.grpc.HandleMessageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.elasticsoftware.elasticactors.grpc.HandleMessageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.elasticsoftware.elasticactors.grpc.HandleMessageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.elasticsoftware.elasticactors.grpc.HandleMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.elasticsoftware.elasticactors.grpc.HandleMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.elasticsoftware.elasticactors.grpc.HandleMessageRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The request message with the actor name.
   * </pre>
   *
   * Protobuf type {@code org.elasticsoftware.elasticactors.grpc.HandleMessageRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.elasticsoftware.elasticactors.grpc.HandleMessageRequest)
      org.elasticsoftware.elasticactors.grpc.HandleMessageRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.elasticsoftware.elasticactors.grpc.Services.internal_static_org_elasticsoftware_elasticactors_grpc_HandleMessageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.elasticsoftware.elasticactors.grpc.Services.internal_static_org_elasticsoftware_elasticactors_grpc_HandleMessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.elasticsoftware.elasticactors.grpc.HandleMessageRequest.class, org.elasticsoftware.elasticactors.grpc.HandleMessageRequest.Builder.class);
    }

    // Construct using org.elasticsoftware.elasticactors.grpc.HandleMessageRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (messageBuilder_ == null) {
        message_ = null;
      } else {
        message_ = null;
        messageBuilder_ = null;
      }
      if (stateBuilder_ == null) {
        state_ = null;
      } else {
        state_ = null;
        stateBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.elasticsoftware.elasticactors.grpc.Services.internal_static_org_elasticsoftware_elasticactors_grpc_HandleMessageRequest_descriptor;
    }

    @java.lang.Override
    public org.elasticsoftware.elasticactors.grpc.HandleMessageRequest getDefaultInstanceForType() {
      return org.elasticsoftware.elasticactors.grpc.HandleMessageRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.elasticsoftware.elasticactors.grpc.HandleMessageRequest build() {
      org.elasticsoftware.elasticactors.grpc.HandleMessageRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.elasticsoftware.elasticactors.grpc.HandleMessageRequest buildPartial() {
      org.elasticsoftware.elasticactors.grpc.HandleMessageRequest result = new org.elasticsoftware.elasticactors.grpc.HandleMessageRequest(this);
      if (messageBuilder_ == null) {
        result.message_ = message_;
      } else {
        result.message_ = messageBuilder_.build();
      }
      if (stateBuilder_ == null) {
        result.state_ = state_;
      } else {
        result.state_ = stateBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.elasticsoftware.elasticactors.grpc.HandleMessageRequest) {
        return mergeFrom((org.elasticsoftware.elasticactors.grpc.HandleMessageRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.elasticsoftware.elasticactors.grpc.HandleMessageRequest other) {
      if (other == org.elasticsoftware.elasticactors.grpc.HandleMessageRequest.getDefaultInstance()) return this;
      if (other.hasMessage()) {
        mergeMessage(other.getMessage());
      }
      if (other.hasState()) {
        mergeState(other.getState());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.elasticsoftware.elasticactors.grpc.HandleMessageRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.elasticsoftware.elasticactors.grpc.HandleMessageRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.elasticsoftware.elasticactors.grpc.InternalMessage message_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.elasticsoftware.elasticactors.grpc.InternalMessage, org.elasticsoftware.elasticactors.grpc.InternalMessage.Builder, org.elasticsoftware.elasticactors.grpc.InternalMessageOrBuilder> messageBuilder_;
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.InternalMessage message = 1;</code>
     * @return Whether the message field is set.
     */
    public boolean hasMessage() {
      return messageBuilder_ != null || message_ != null;
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.InternalMessage message = 1;</code>
     * @return The message.
     */
    public org.elasticsoftware.elasticactors.grpc.InternalMessage getMessage() {
      if (messageBuilder_ == null) {
        return message_ == null ? org.elasticsoftware.elasticactors.grpc.InternalMessage.getDefaultInstance() : message_;
      } else {
        return messageBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.InternalMessage message = 1;</code>
     */
    public Builder setMessage(org.elasticsoftware.elasticactors.grpc.InternalMessage value) {
      if (messageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        messageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.InternalMessage message = 1;</code>
     */
    public Builder setMessage(
        org.elasticsoftware.elasticactors.grpc.InternalMessage.Builder builderForValue) {
      if (messageBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        messageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.InternalMessage message = 1;</code>
     */
    public Builder mergeMessage(org.elasticsoftware.elasticactors.grpc.InternalMessage value) {
      if (messageBuilder_ == null) {
        if (message_ != null) {
          message_ =
            org.elasticsoftware.elasticactors.grpc.InternalMessage.newBuilder(message_).mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        messageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.InternalMessage message = 1;</code>
     */
    public Builder clearMessage() {
      if (messageBuilder_ == null) {
        message_ = null;
        onChanged();
      } else {
        message_ = null;
        messageBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.InternalMessage message = 1;</code>
     */
    public org.elasticsoftware.elasticactors.grpc.InternalMessage.Builder getMessageBuilder() {
      
      onChanged();
      return getMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.InternalMessage message = 1;</code>
     */
    public org.elasticsoftware.elasticactors.grpc.InternalMessageOrBuilder getMessageOrBuilder() {
      if (messageBuilder_ != null) {
        return messageBuilder_.getMessageOrBuilder();
      } else {
        return message_ == null ?
            org.elasticsoftware.elasticactors.grpc.InternalMessage.getDefaultInstance() : message_;
      }
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.InternalMessage message = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.elasticsoftware.elasticactors.grpc.InternalMessage, org.elasticsoftware.elasticactors.grpc.InternalMessage.Builder, org.elasticsoftware.elasticactors.grpc.InternalMessageOrBuilder> 
        getMessageFieldBuilder() {
      if (messageBuilder_ == null) {
        messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.elasticsoftware.elasticactors.grpc.InternalMessage, org.elasticsoftware.elasticactors.grpc.InternalMessage.Builder, org.elasticsoftware.elasticactors.grpc.InternalMessageOrBuilder>(
                getMessage(),
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      return messageBuilder_;
    }

    private org.elasticsoftware.elasticactors.grpc.ActorState state_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.elasticsoftware.elasticactors.grpc.ActorState, org.elasticsoftware.elasticactors.grpc.ActorState.Builder, org.elasticsoftware.elasticactors.grpc.ActorStateOrBuilder> stateBuilder_;
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
     * @return Whether the state field is set.
     */
    public boolean hasState() {
      return stateBuilder_ != null || state_ != null;
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
     * @return The state.
     */
    public org.elasticsoftware.elasticactors.grpc.ActorState getState() {
      if (stateBuilder_ == null) {
        return state_ == null ? org.elasticsoftware.elasticactors.grpc.ActorState.getDefaultInstance() : state_;
      } else {
        return stateBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
     */
    public Builder setState(org.elasticsoftware.elasticactors.grpc.ActorState value) {
      if (stateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        state_ = value;
        onChanged();
      } else {
        stateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
     */
    public Builder setState(
        org.elasticsoftware.elasticactors.grpc.ActorState.Builder builderForValue) {
      if (stateBuilder_ == null) {
        state_ = builderForValue.build();
        onChanged();
      } else {
        stateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
     */
    public Builder mergeState(org.elasticsoftware.elasticactors.grpc.ActorState value) {
      if (stateBuilder_ == null) {
        if (state_ != null) {
          state_ =
            org.elasticsoftware.elasticactors.grpc.ActorState.newBuilder(state_).mergeFrom(value).buildPartial();
        } else {
          state_ = value;
        }
        onChanged();
      } else {
        stateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
     */
    public Builder clearState() {
      if (stateBuilder_ == null) {
        state_ = null;
        onChanged();
      } else {
        state_ = null;
        stateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
     */
    public org.elasticsoftware.elasticactors.grpc.ActorState.Builder getStateBuilder() {
      
      onChanged();
      return getStateFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
     */
    public org.elasticsoftware.elasticactors.grpc.ActorStateOrBuilder getStateOrBuilder() {
      if (stateBuilder_ != null) {
        return stateBuilder_.getMessageOrBuilder();
      } else {
        return state_ == null ?
            org.elasticsoftware.elasticactors.grpc.ActorState.getDefaultInstance() : state_;
      }
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.grpc.ActorState state = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.elasticsoftware.elasticactors.grpc.ActorState, org.elasticsoftware.elasticactors.grpc.ActorState.Builder, org.elasticsoftware.elasticactors.grpc.ActorStateOrBuilder> 
        getStateFieldBuilder() {
      if (stateBuilder_ == null) {
        stateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.elasticsoftware.elasticactors.grpc.ActorState, org.elasticsoftware.elasticactors.grpc.ActorState.Builder, org.elasticsoftware.elasticactors.grpc.ActorStateOrBuilder>(
                getState(),
                getParentForChildren(),
                isClean());
        state_ = null;
      }
      return stateBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.elasticsoftware.elasticactors.grpc.HandleMessageRequest)
  }

  // @@protoc_insertion_point(class_scope:org.elasticsoftware.elasticactors.grpc.HandleMessageRequest)
  private static final org.elasticsoftware.elasticactors.grpc.HandleMessageRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.elasticsoftware.elasticactors.grpc.HandleMessageRequest();
  }

  public static org.elasticsoftware.elasticactors.grpc.HandleMessageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HandleMessageRequest>
      PARSER = new com.google.protobuf.AbstractParser<HandleMessageRequest>() {
    @java.lang.Override
    public HandleMessageRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HandleMessageRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HandleMessageRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HandleMessageRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.elasticsoftware.elasticactors.grpc.HandleMessageRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

