// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package org.elasticsoftware.elasticactors.grpc;

public interface InternalMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.elasticsoftware.elasticactors.grpc.InternalMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string receiver = 1;</code>
   * @return The receiver.
   */
  java.lang.String getReceiver();
  /**
   * <code>string receiver = 1;</code>
   * @return The bytes for receiver.
   */
  com.google.protobuf.ByteString
      getReceiverBytes();

  /**
   * <code>string sender = 2;</code>
   * @return The sender.
   */
  java.lang.String getSender();
  /**
   * <code>string sender = 2;</code>
   * @return The bytes for sender.
   */
  com.google.protobuf.ByteString
      getSenderBytes();

  /**
   * <code>string payloadType = 3;</code>
   * @return The payloadType.
   */
  java.lang.String getPayloadType();
  /**
   * <code>string payloadType = 3;</code>
   * @return The bytes for payloadType.
   */
  com.google.protobuf.ByteString
      getPayloadTypeBytes();

  /**
   * <code>bytes payload = 4;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();

  /**
   * <code>bytes id = 5;</code>
   * @return The id.
   */
  com.google.protobuf.ByteString getId();

  /**
   * <code>bool durable = 6;</code>
   * @return The durable.
   */
  boolean getDurable();

  /**
   * <code>bool undeliverable = 7;</code>
   * @return The undeliverable.
   */
  boolean getUndeliverable();

  /**
   * <code>repeated string receivers = 8;</code>
   * @return A list containing the receivers.
   */
  java.util.List<java.lang.String>
      getReceiversList();
  /**
   * <code>repeated string receivers = 8;</code>
   * @return The count of receivers.
   */
  int getReceiversCount();
  /**
   * <code>repeated string receivers = 8;</code>
   * @param index The index of the element to return.
   * @return The receivers at the given index.
   */
  java.lang.String getReceivers(int index);
  /**
   * <code>repeated string receivers = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the receivers at the given index.
   */
  com.google.protobuf.ByteString
      getReceiversBytes(int index);

  /**
   * <code>uint32 timeout = 9;</code>
   * @return The timeout.
   */
  int getTimeout();
}
