// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package org.elasticsoftware.elasticactors.grpc;

/**
 * Protobuf type {@code org.elasticsoftware.elasticactors.grpc.InternalMessage}
 */
public  final class InternalMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.elasticsoftware.elasticactors.grpc.InternalMessage)
    InternalMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InternalMessage.newBuilder() to construct.
  private InternalMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InternalMessage() {
    receiver_ = "";
    sender_ = "";
    payloadType_ = "";
    payload_ = com.google.protobuf.ByteString.EMPTY;
    id_ = com.google.protobuf.ByteString.EMPTY;
    receivers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InternalMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InternalMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            receiver_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            sender_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            payloadType_ = s;
            break;
          }
          case 34: {

            payload_ = input.readBytes();
            break;
          }
          case 42: {

            id_ = input.readBytes();
            break;
          }
          case 48: {

            durable_ = input.readBool();
            break;
          }
          case 56: {

            undeliverable_ = input.readBool();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              receivers_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            receivers_.add(s);
            break;
          }
          case 72: {

            timeout_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        receivers_ = receivers_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.elasticsoftware.elasticactors.grpc.Services.internal_static_org_elasticsoftware_elasticactors_grpc_InternalMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.elasticsoftware.elasticactors.grpc.Services.internal_static_org_elasticsoftware_elasticactors_grpc_InternalMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.elasticsoftware.elasticactors.grpc.InternalMessage.class, org.elasticsoftware.elasticactors.grpc.InternalMessage.Builder.class);
  }

  public static final int RECEIVER_FIELD_NUMBER = 1;
  private volatile java.lang.Object receiver_;
  /**
   * <code>string receiver = 1;</code>
   * @return The receiver.
   */
  public java.lang.String getReceiver() {
    java.lang.Object ref = receiver_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      receiver_ = s;
      return s;
    }
  }
  /**
   * <code>string receiver = 1;</code>
   * @return The bytes for receiver.
   */
  public com.google.protobuf.ByteString
      getReceiverBytes() {
    java.lang.Object ref = receiver_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      receiver_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SENDER_FIELD_NUMBER = 2;
  private volatile java.lang.Object sender_;
  /**
   * <code>string sender = 2;</code>
   * @return The sender.
   */
  public java.lang.String getSender() {
    java.lang.Object ref = sender_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sender_ = s;
      return s;
    }
  }
  /**
   * <code>string sender = 2;</code>
   * @return The bytes for sender.
   */
  public com.google.protobuf.ByteString
      getSenderBytes() {
    java.lang.Object ref = sender_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sender_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAYLOADTYPE_FIELD_NUMBER = 3;
  private volatile java.lang.Object payloadType_;
  /**
   * <code>string payloadType = 3;</code>
   * @return The payloadType.
   */
  public java.lang.String getPayloadType() {
    java.lang.Object ref = payloadType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      payloadType_ = s;
      return s;
    }
  }
  /**
   * <code>string payloadType = 3;</code>
   * @return The bytes for payloadType.
   */
  public com.google.protobuf.ByteString
      getPayloadTypeBytes() {
    java.lang.Object ref = payloadType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      payloadType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAYLOAD_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString payload_;
  /**
   * <code>bytes payload = 4;</code>
   * @return The payload.
   */
  public com.google.protobuf.ByteString getPayload() {
    return payload_;
  }

  public static final int ID_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString id_;
  /**
   * <code>bytes id = 5;</code>
   * @return The id.
   */
  public com.google.protobuf.ByteString getId() {
    return id_;
  }

  public static final int DURABLE_FIELD_NUMBER = 6;
  private boolean durable_;
  /**
   * <code>bool durable = 6;</code>
   * @return The durable.
   */
  public boolean getDurable() {
    return durable_;
  }

  public static final int UNDELIVERABLE_FIELD_NUMBER = 7;
  private boolean undeliverable_;
  /**
   * <code>bool undeliverable = 7;</code>
   * @return The undeliverable.
   */
  public boolean getUndeliverable() {
    return undeliverable_;
  }

  public static final int RECEIVERS_FIELD_NUMBER = 8;
  private com.google.protobuf.LazyStringList receivers_;
  /**
   * <code>repeated string receivers = 8;</code>
   * @return A list containing the receivers.
   */
  public com.google.protobuf.ProtocolStringList
      getReceiversList() {
    return receivers_;
  }
  /**
   * <code>repeated string receivers = 8;</code>
   * @return The count of receivers.
   */
  public int getReceiversCount() {
    return receivers_.size();
  }
  /**
   * <code>repeated string receivers = 8;</code>
   * @param index The index of the element to return.
   * @return The receivers at the given index.
   */
  public java.lang.String getReceivers(int index) {
    return receivers_.get(index);
  }
  /**
   * <code>repeated string receivers = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the receivers at the given index.
   */
  public com.google.protobuf.ByteString
      getReceiversBytes(int index) {
    return receivers_.getByteString(index);
  }

  public static final int TIMEOUT_FIELD_NUMBER = 9;
  private int timeout_;
  /**
   * <code>uint32 timeout = 9;</code>
   * @return The timeout.
   */
  public int getTimeout() {
    return timeout_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getReceiverBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, receiver_);
    }
    if (!getSenderBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sender_);
    }
    if (!getPayloadTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, payloadType_);
    }
    if (!payload_.isEmpty()) {
      output.writeBytes(4, payload_);
    }
    if (!id_.isEmpty()) {
      output.writeBytes(5, id_);
    }
    if (durable_ != false) {
      output.writeBool(6, durable_);
    }
    if (undeliverable_ != false) {
      output.writeBool(7, undeliverable_);
    }
    for (int i = 0; i < receivers_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, receivers_.getRaw(i));
    }
    if (timeout_ != 0) {
      output.writeUInt32(9, timeout_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getReceiverBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, receiver_);
    }
    if (!getSenderBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sender_);
    }
    if (!getPayloadTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, payloadType_);
    }
    if (!payload_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, payload_);
    }
    if (!id_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, id_);
    }
    if (durable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, durable_);
    }
    if (undeliverable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, undeliverable_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < receivers_.size(); i++) {
        dataSize += computeStringSizeNoTag(receivers_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getReceiversList().size();
    }
    if (timeout_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(9, timeout_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.elasticsoftware.elasticactors.grpc.InternalMessage)) {
      return super.equals(obj);
    }
    org.elasticsoftware.elasticactors.grpc.InternalMessage other = (org.elasticsoftware.elasticactors.grpc.InternalMessage) obj;

    if (!getReceiver()
        .equals(other.getReceiver())) return false;
    if (!getSender()
        .equals(other.getSender())) return false;
    if (!getPayloadType()
        .equals(other.getPayloadType())) return false;
    if (!getPayload()
        .equals(other.getPayload())) return false;
    if (!getId()
        .equals(other.getId())) return false;
    if (getDurable()
        != other.getDurable()) return false;
    if (getUndeliverable()
        != other.getUndeliverable()) return false;
    if (!getReceiversList()
        .equals(other.getReceiversList())) return false;
    if (getTimeout()
        != other.getTimeout()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
    hash = (53 * hash) + getReceiver().hashCode();
    hash = (37 * hash) + SENDER_FIELD_NUMBER;
    hash = (53 * hash) + getSender().hashCode();
    hash = (37 * hash) + PAYLOADTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getPayloadType().hashCode();
    hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getPayload().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + DURABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDurable());
    hash = (37 * hash) + UNDELIVERABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getUndeliverable());
    if (getReceiversCount() > 0) {
      hash = (37 * hash) + RECEIVERS_FIELD_NUMBER;
      hash = (53 * hash) + getReceiversList().hashCode();
    }
    hash = (37 * hash) + TIMEOUT_FIELD_NUMBER;
    hash = (53 * hash) + getTimeout();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.elasticsoftware.elasticactors.grpc.InternalMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.elasticsoftware.elasticactors.grpc.InternalMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.elasticsoftware.elasticactors.grpc.InternalMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.elasticsoftware.elasticactors.grpc.InternalMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.elasticsoftware.elasticactors.grpc.InternalMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.elasticsoftware.elasticactors.grpc.InternalMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.elasticsoftware.elasticactors.grpc.InternalMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.elasticsoftware.elasticactors.grpc.InternalMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.elasticsoftware.elasticactors.grpc.InternalMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.elasticsoftware.elasticactors.grpc.InternalMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.elasticsoftware.elasticactors.grpc.InternalMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.elasticsoftware.elasticactors.grpc.InternalMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.elasticsoftware.elasticactors.grpc.InternalMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.elasticsoftware.elasticactors.grpc.InternalMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.elasticsoftware.elasticactors.grpc.InternalMessage)
      org.elasticsoftware.elasticactors.grpc.InternalMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.elasticsoftware.elasticactors.grpc.Services.internal_static_org_elasticsoftware_elasticactors_grpc_InternalMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.elasticsoftware.elasticactors.grpc.Services.internal_static_org_elasticsoftware_elasticactors_grpc_InternalMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.elasticsoftware.elasticactors.grpc.InternalMessage.class, org.elasticsoftware.elasticactors.grpc.InternalMessage.Builder.class);
    }

    // Construct using org.elasticsoftware.elasticactors.grpc.InternalMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      receiver_ = "";

      sender_ = "";

      payloadType_ = "";

      payload_ = com.google.protobuf.ByteString.EMPTY;

      id_ = com.google.protobuf.ByteString.EMPTY;

      durable_ = false;

      undeliverable_ = false;

      receivers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      timeout_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.elasticsoftware.elasticactors.grpc.Services.internal_static_org_elasticsoftware_elasticactors_grpc_InternalMessage_descriptor;
    }

    @java.lang.Override
    public org.elasticsoftware.elasticactors.grpc.InternalMessage getDefaultInstanceForType() {
      return org.elasticsoftware.elasticactors.grpc.InternalMessage.getDefaultInstance();
    }

    @java.lang.Override
    public org.elasticsoftware.elasticactors.grpc.InternalMessage build() {
      org.elasticsoftware.elasticactors.grpc.InternalMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.elasticsoftware.elasticactors.grpc.InternalMessage buildPartial() {
      org.elasticsoftware.elasticactors.grpc.InternalMessage result = new org.elasticsoftware.elasticactors.grpc.InternalMessage(this);
      int from_bitField0_ = bitField0_;
      result.receiver_ = receiver_;
      result.sender_ = sender_;
      result.payloadType_ = payloadType_;
      result.payload_ = payload_;
      result.id_ = id_;
      result.durable_ = durable_;
      result.undeliverable_ = undeliverable_;
      if (((bitField0_ & 0x00000001) != 0)) {
        receivers_ = receivers_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.receivers_ = receivers_;
      result.timeout_ = timeout_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.elasticsoftware.elasticactors.grpc.InternalMessage) {
        return mergeFrom((org.elasticsoftware.elasticactors.grpc.InternalMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.elasticsoftware.elasticactors.grpc.InternalMessage other) {
      if (other == org.elasticsoftware.elasticactors.grpc.InternalMessage.getDefaultInstance()) return this;
      if (!other.getReceiver().isEmpty()) {
        receiver_ = other.receiver_;
        onChanged();
      }
      if (!other.getSender().isEmpty()) {
        sender_ = other.sender_;
        onChanged();
      }
      if (!other.getPayloadType().isEmpty()) {
        payloadType_ = other.payloadType_;
        onChanged();
      }
      if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
        setPayload(other.getPayload());
      }
      if (other.getId() != com.google.protobuf.ByteString.EMPTY) {
        setId(other.getId());
      }
      if (other.getDurable() != false) {
        setDurable(other.getDurable());
      }
      if (other.getUndeliverable() != false) {
        setUndeliverable(other.getUndeliverable());
      }
      if (!other.receivers_.isEmpty()) {
        if (receivers_.isEmpty()) {
          receivers_ = other.receivers_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureReceiversIsMutable();
          receivers_.addAll(other.receivers_);
        }
        onChanged();
      }
      if (other.getTimeout() != 0) {
        setTimeout(other.getTimeout());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.elasticsoftware.elasticactors.grpc.InternalMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.elasticsoftware.elasticactors.grpc.InternalMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object receiver_ = "";
    /**
     * <code>string receiver = 1;</code>
     * @return The receiver.
     */
    public java.lang.String getReceiver() {
      java.lang.Object ref = receiver_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiver_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string receiver = 1;</code>
     * @return The bytes for receiver.
     */
    public com.google.protobuf.ByteString
        getReceiverBytes() {
      java.lang.Object ref = receiver_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string receiver = 1;</code>
     * @param value The receiver to set.
     * @return This builder for chaining.
     */
    public Builder setReceiver(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      receiver_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string receiver = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiver() {
      
      receiver_ = getDefaultInstance().getReceiver();
      onChanged();
      return this;
    }
    /**
     * <code>string receiver = 1;</code>
     * @param value The bytes for receiver to set.
     * @return This builder for chaining.
     */
    public Builder setReceiverBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      receiver_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sender_ = "";
    /**
     * <code>string sender = 2;</code>
     * @return The sender.
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sender_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sender = 2;</code>
     * @return The bytes for sender.
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sender = 2;</code>
     * @param value The sender to set.
     * @return This builder for chaining.
     */
    public Builder setSender(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sender_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sender = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSender() {
      
      sender_ = getDefaultInstance().getSender();
      onChanged();
      return this;
    }
    /**
     * <code>string sender = 2;</code>
     * @param value The bytes for sender to set.
     * @return This builder for chaining.
     */
    public Builder setSenderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sender_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object payloadType_ = "";
    /**
     * <code>string payloadType = 3;</code>
     * @return The payloadType.
     */
    public java.lang.String getPayloadType() {
      java.lang.Object ref = payloadType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        payloadType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string payloadType = 3;</code>
     * @return The bytes for payloadType.
     */
    public com.google.protobuf.ByteString
        getPayloadTypeBytes() {
      java.lang.Object ref = payloadType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payloadType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string payloadType = 3;</code>
     * @param value The payloadType to set.
     * @return This builder for chaining.
     */
    public Builder setPayloadType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      payloadType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string payloadType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayloadType() {
      
      payloadType_ = getDefaultInstance().getPayloadType();
      onChanged();
      return this;
    }
    /**
     * <code>string payloadType = 3;</code>
     * @param value The bytes for payloadType to set.
     * @return This builder for chaining.
     */
    public Builder setPayloadTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      payloadType_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes payload = 4;</code>
     * @return The payload.
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }
    /**
     * <code>bytes payload = 4;</code>
     * @param value The payload to set.
     * @return This builder for chaining.
     */
    public Builder setPayload(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      payload_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes payload = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayload() {
      
      payload_ = getDefaultInstance().getPayload();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes id = 5;</code>
     * @return The id.
     */
    public com.google.protobuf.ByteString getId() {
      return id_;
    }
    /**
     * <code>bytes id = 5;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }

    private boolean durable_ ;
    /**
     * <code>bool durable = 6;</code>
     * @return The durable.
     */
    public boolean getDurable() {
      return durable_;
    }
    /**
     * <code>bool durable = 6;</code>
     * @param value The durable to set.
     * @return This builder for chaining.
     */
    public Builder setDurable(boolean value) {
      
      durable_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool durable = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDurable() {
      
      durable_ = false;
      onChanged();
      return this;
    }

    private boolean undeliverable_ ;
    /**
     * <code>bool undeliverable = 7;</code>
     * @return The undeliverable.
     */
    public boolean getUndeliverable() {
      return undeliverable_;
    }
    /**
     * <code>bool undeliverable = 7;</code>
     * @param value The undeliverable to set.
     * @return This builder for chaining.
     */
    public Builder setUndeliverable(boolean value) {
      
      undeliverable_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool undeliverable = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearUndeliverable() {
      
      undeliverable_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList receivers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureReceiversIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        receivers_ = new com.google.protobuf.LazyStringArrayList(receivers_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string receivers = 8;</code>
     * @return A list containing the receivers.
     */
    public com.google.protobuf.ProtocolStringList
        getReceiversList() {
      return receivers_.getUnmodifiableView();
    }
    /**
     * <code>repeated string receivers = 8;</code>
     * @return The count of receivers.
     */
    public int getReceiversCount() {
      return receivers_.size();
    }
    /**
     * <code>repeated string receivers = 8;</code>
     * @param index The index of the element to return.
     * @return The receivers at the given index.
     */
    public java.lang.String getReceivers(int index) {
      return receivers_.get(index);
    }
    /**
     * <code>repeated string receivers = 8;</code>
     * @param index The index of the value to return.
     * @return The bytes of the receivers at the given index.
     */
    public com.google.protobuf.ByteString
        getReceiversBytes(int index) {
      return receivers_.getByteString(index);
    }
    /**
     * <code>repeated string receivers = 8;</code>
     * @param index The index to set the value at.
     * @param value The receivers to set.
     * @return This builder for chaining.
     */
    public Builder setReceivers(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureReceiversIsMutable();
      receivers_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string receivers = 8;</code>
     * @param value The receivers to add.
     * @return This builder for chaining.
     */
    public Builder addReceivers(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureReceiversIsMutable();
      receivers_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string receivers = 8;</code>
     * @param values The receivers to add.
     * @return This builder for chaining.
     */
    public Builder addAllReceivers(
        java.lang.Iterable<java.lang.String> values) {
      ensureReceiversIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, receivers_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string receivers = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceivers() {
      receivers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string receivers = 8;</code>
     * @param value The bytes of the receivers to add.
     * @return This builder for chaining.
     */
    public Builder addReceiversBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureReceiversIsMutable();
      receivers_.add(value);
      onChanged();
      return this;
    }

    private int timeout_ ;
    /**
     * <code>uint32 timeout = 9;</code>
     * @return The timeout.
     */
    public int getTimeout() {
      return timeout_;
    }
    /**
     * <code>uint32 timeout = 9;</code>
     * @param value The timeout to set.
     * @return This builder for chaining.
     */
    public Builder setTimeout(int value) {
      
      timeout_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 timeout = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeout() {
      
      timeout_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.elasticsoftware.elasticactors.grpc.InternalMessage)
  }

  // @@protoc_insertion_point(class_scope:org.elasticsoftware.elasticactors.grpc.InternalMessage)
  private static final org.elasticsoftware.elasticactors.grpc.InternalMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.elasticsoftware.elasticactors.grpc.InternalMessage();
  }

  public static org.elasticsoftware.elasticactors.grpc.InternalMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InternalMessage>
      PARSER = new com.google.protobuf.AbstractParser<InternalMessage>() {
    @java.lang.Override
    public InternalMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InternalMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InternalMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InternalMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.elasticsoftware.elasticactors.grpc.InternalMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

