// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package org.elasticsoftware.elasticactors.grpc;

public final class Services {
  private Services() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_elasticsoftware_elasticactors_grpc_HandleMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_elasticsoftware_elasticactors_grpc_HandleMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_elasticsoftware_elasticactors_grpc_ActorLifecycleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_elasticsoftware_elasticactors_grpc_ActorLifecycleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_elasticsoftware_elasticactors_grpc_InternalMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_elasticsoftware_elasticactors_grpc_InternalMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_elasticsoftware_elasticactors_grpc_ActorState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_elasticsoftware_elasticactors_grpc_ActorState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016services.proto\022&org.elasticsoftware.el" +
      "asticactors.grpc\"\243\001\n\024HandleMessageReques" +
      "t\022H\n\007message\030\001 \001(\01327.org.elasticsoftware" +
      ".elasticactors.grpc.InternalMessage\022A\n\005s" +
      "tate\030\002 \001(\01322.org.elasticsoftware.elastic" +
      "actors.grpc.ActorState\"\246\001\n\026ActorLifecycl" +
      "eResponse\022I\n\010messages\030\001 \003(\01327.org.elasti" +
      "csoftware.elasticactors.grpc.InternalMes" +
      "sage\022A\n\005state\030\002 \001(\01322.org.elasticsoftwar" +
      "e.elasticactors.grpc.ActorState\"\261\001\n\017Inte" +
      "rnalMessage\022\020\n\010receiver\030\001 \001(\t\022\016\n\006sender\030" +
      "\002 \001(\t\022\023\n\013payloadType\030\003 \001(\t\022\017\n\007payload\030\004 " +
      "\001(\014\022\n\n\002id\030\005 \001(\014\022\017\n\007durable\030\006 \001(\010\022\025\n\runde" +
      "liverable\030\007 \001(\010\022\021\n\treceivers\030\010 \003(\t\022\017\n\007ti" +
      "meout\030\t \001(\r\"O\n\nActorState\022\r\n\005state\030\001 \001(\014" +
      "\022\027\n\017stateGeneration\030\002 \001(\004\022\031\n\021compression" +
      "Method\030\003 \001(\t2\251\001\n\025ActorLifecycleService\022\217" +
      "\001\n\rHandleMessage\022<.org.elasticsoftware.e" +
      "lasticactors.grpc.HandleMessageRequest\032>" +
      ".org.elasticsoftware.elasticactors.grpc." +
      "ActorLifecycleResponse\"\000B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_elasticsoftware_elasticactors_grpc_HandleMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_elasticsoftware_elasticactors_grpc_HandleMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_elasticsoftware_elasticactors_grpc_HandleMessageRequest_descriptor,
        new java.lang.String[] { "Message", "State", });
    internal_static_org_elasticsoftware_elasticactors_grpc_ActorLifecycleResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_elasticsoftware_elasticactors_grpc_ActorLifecycleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_elasticsoftware_elasticactors_grpc_ActorLifecycleResponse_descriptor,
        new java.lang.String[] { "Messages", "State", });
    internal_static_org_elasticsoftware_elasticactors_grpc_InternalMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_elasticsoftware_elasticactors_grpc_InternalMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_elasticsoftware_elasticactors_grpc_InternalMessage_descriptor,
        new java.lang.String[] { "Receiver", "Sender", "PayloadType", "Payload", "Id", "Durable", "Undeliverable", "Receivers", "Timeout", });
    internal_static_org_elasticsoftware_elasticactors_grpc_ActorState_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_elasticsoftware_elasticactors_grpc_ActorState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_elasticsoftware_elasticactors_grpc_ActorState_descriptor,
        new java.lang.String[] { "State", "StateGeneration", "CompressionMethod", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
