/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.elasticsoftware.elasticactors.cloudnative.operator.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.elasticsoftware.elasticactors.cloudnative.operator.models.V1ActorSystemSpecActorGateway;
import org.elasticsoftware.elasticactors.cloudnative.operator.models.V1ActorSystemSpecPersistentActors;
import org.elasticsoftware.elasticactors.cloudnative.operator.models.V1ActorSystemSpecRuntime;

/**
 * V1ActorSystemSpec
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-05T13:31:51.618Z[Etc/UTC]")
public class V1ActorSystemSpec {
  public static final String SERIALIZED_NAME_ACTOR_GATEWAY = "actorGateway";
  @SerializedName(SERIALIZED_NAME_ACTOR_GATEWAY)
  private V1ActorSystemSpecActorGateway actorGateway;

  public static final String SERIALIZED_NAME_PERSISTENT_ACTORS = "persistentActors";
  @SerializedName(SERIALIZED_NAME_PERSISTENT_ACTORS)
  private List<V1ActorSystemSpecPersistentActors> persistentActors = null;

  public static final String SERIALIZED_NAME_RUNTIME = "runtime";
  @SerializedName(SERIALIZED_NAME_RUNTIME)
  private V1ActorSystemSpecRuntime runtime;

  public static final String SERIALIZED_NAME_SERVICE_ACTORS = "serviceActors";
  @SerializedName(SERIALIZED_NAME_SERVICE_ACTORS)
  private List<V1ActorSystemSpecPersistentActors> serviceActors = null;

  public static final String SERIALIZED_NAME_SHARDS = "shards";
  @SerializedName(SERIALIZED_NAME_SHARDS)
  private Integer shards;


  public V1ActorSystemSpec actorGateway(V1ActorSystemSpecActorGateway actorGateway) {
    
    this.actorGateway = actorGateway;
    return this;
  }

   /**
   * Get actorGateway
   * @return actorGateway
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ActorSystemSpecActorGateway getActorGateway() {
    return actorGateway;
  }


  public void setActorGateway(V1ActorSystemSpecActorGateway actorGateway) {
    this.actorGateway = actorGateway;
  }


  public V1ActorSystemSpec persistentActors(List<V1ActorSystemSpecPersistentActors> persistentActors) {
    
    this.persistentActors = persistentActors;
    return this;
  }

  public V1ActorSystemSpec addPersistentActorsItem(V1ActorSystemSpecPersistentActors persistentActorsItem) {
    if (this.persistentActors == null) {
      this.persistentActors = new ArrayList<>();
    }
    this.persistentActors.add(persistentActorsItem);
    return this;
  }

   /**
   * Get persistentActors
   * @return persistentActors
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1ActorSystemSpecPersistentActors> getPersistentActors() {
    return persistentActors;
  }


  public void setPersistentActors(List<V1ActorSystemSpecPersistentActors> persistentActors) {
    this.persistentActors = persistentActors;
  }


  public V1ActorSystemSpec runtime(V1ActorSystemSpecRuntime runtime) {
    
    this.runtime = runtime;
    return this;
  }

   /**
   * Get runtime
   * @return runtime
  **/
  @ApiModelProperty(required = true, value = "")

  public V1ActorSystemSpecRuntime getRuntime() {
    return runtime;
  }


  public void setRuntime(V1ActorSystemSpecRuntime runtime) {
    this.runtime = runtime;
  }


  public V1ActorSystemSpec serviceActors(List<V1ActorSystemSpecPersistentActors> serviceActors) {
    
    this.serviceActors = serviceActors;
    return this;
  }

  public V1ActorSystemSpec addServiceActorsItem(V1ActorSystemSpecPersistentActors serviceActorsItem) {
    if (this.serviceActors == null) {
      this.serviceActors = new ArrayList<>();
    }
    this.serviceActors.add(serviceActorsItem);
    return this;
  }

   /**
   * Get serviceActors
   * @return serviceActors
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1ActorSystemSpecPersistentActors> getServiceActors() {
    return serviceActors;
  }


  public void setServiceActors(List<V1ActorSystemSpecPersistentActors> serviceActors) {
    this.serviceActors = serviceActors;
  }


  public V1ActorSystemSpec shards(Integer shards) {
    
    this.shards = shards;
    return this;
  }

   /**
   * Get shards
   * @return shards
  **/
  @ApiModelProperty(required = true, value = "")

  public Integer getShards() {
    return shards;
  }


  public void setShards(Integer shards) {
    this.shards = shards;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1ActorSystemSpec v1ActorSystemSpec = (V1ActorSystemSpec) o;
    return Objects.equals(this.actorGateway, v1ActorSystemSpec.actorGateway) &&
        Objects.equals(this.persistentActors, v1ActorSystemSpec.persistentActors) &&
        Objects.equals(this.runtime, v1ActorSystemSpec.runtime) &&
        Objects.equals(this.serviceActors, v1ActorSystemSpec.serviceActors) &&
        Objects.equals(this.shards, v1ActorSystemSpec.shards);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actorGateway, persistentActors, runtime, serviceActors, shards);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1ActorSystemSpec {\n");
    sb.append("    actorGateway: ").append(toIndentedString(actorGateway)).append("\n");
    sb.append("    persistentActors: ").append(toIndentedString(persistentActors)).append("\n");
    sb.append("    runtime: ").append(toIndentedString(runtime)).append("\n");
    sb.append("    serviceActors: ").append(toIndentedString(serviceActors)).append("\n");
    sb.append("    shards: ").append(toIndentedString(shards)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

