---
micronaut:
  application:
    name: actornode-micronaut

---
#rabbitmq:
#  uri: amqp://localhost:5672

---
cassandra:
  default:
    clusterName: "myCluster"
    contactPoint: "localhost"
    port: 9042
    maxSchemaAgreementWaitSeconds: 20
    ssl: true

---
micronaut:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

---
kafka:
  bootstrap:
    servers: localhost:9092
