---
micronaut:
  application:
    name: actornode-micronaut
  config-client:
    enabled: true
---
kubernetes:
  client:
    config-maps:
      enabled: false
      labels:
        - elasticactors.elasticsoftware.org/actorsystem: test-actorsytem
    secrets:
      enabled: true
      labels:
        - elasticactors.elasticsoftware.org/actorsystem: test-actorsystem
---
#rabbitmq:
#  uri: amqp://localhost:5672
---
cassandra:
  default:
    clusterName: "myCluster"
    contactPoint: "localhost"
    port: 9042
    maxSchemaAgreementWaitSeconds: 20
    ssl: true

---
micronaut:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

---
kafka:
  bootstrap:
    servers: localhost:9092
---
grpc:
  client:
    plaintext: true
  channels:
    test-persistentactor:
      address: "${host.ip}:50051"
      plaintext: true
---
elasticactors:
  name: "test-actorsystem"
  nodes: 1
  shards: 8
  persistentactors:
    test-persistentactor:
      enabled: true
      port: 50051

