apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: actorsystems.elasticactors.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: elasticactors.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                shards:
                  type: integer
                persistentActors:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                serviceActors:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                actorGateway:
                  type: object
                  properties:
                    type:
                      type: string
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: actorsystems
    # singular name to be used as an alias on the CLI and for display
    singular: actorsystem
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: ActorSystem
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - as