name: Release Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-maven-test-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-test-
      - name: Setup GraalVM CE
        uses: DeLaGuardo/setup-graalvm@3.1
        with:
          graalvm-version: 22.1.0.java17
      - name: Install Native Image
        run: gu install native-image
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build Operator Docker Image
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
        run: |
          BASE_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          ./mvnw deploy -Dpackaging=docker -Djib.to.tags=${BASE_VERSION}.${{ github.run_number }},${BASE_VERSION} --no-transfer-progress
